# Generated by Django 5.0.6 on 2024-07-23 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrepreneurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('looking_for', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='entreprinder.entrepreneurprofile')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='entreprinder.entrepreneurprofile')),
            ],
            options={
                'unique_together': {('liker', 'liked')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrepreneur1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_first', to='entreprinder.entrepreneurprofile')),
                ('entrepreneur2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_second', to='entreprinder.entrepreneurprofile')),
            ],
            options={
                'unique_together': {('entrepreneur1', 'entrepreneur2')},
            },
        ),
        migrations.CreateModel(
            name='EntrepreneurSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprinder.entrepreneurprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprinder.skill')),
            ],
            options={
                'unique_together': {('entrepreneur', 'skill')},
            },
        ),
    ]
