# Generated by Django 5.0.6 on 2024-08-05 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprinder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrepreneurprofile",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="entreprinder.industry",
            ),
        ),
        migrations.AlterField(
            model_name="entrepreneurprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
