# Generated by Django 5.0.6 on 2024-07-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default-profile.png', null=True, upload_to='profile_pics'),
        ),
    ]
