# Generated by Django 5.0.6 on 2024-07-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprinder', '0002_alter_entrepreneurprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
